### ISSUE TITLE
json Serializer

### ISSUE THREAD

**Issue by MahdiZareie** [s-soroosh/azma-py#10]
for wage_meter we need a json serializer for our HTTP responses.
i had tried <a href='https://pypi.python.org/pypi/django-jsonview'>jsonView</a> but i found it a little weak :-1: 
for now i am using manually implemented methods (json_format) for each model to serialize an object to json format .
can you implement a general decorator function which can serialize every object ( including our model objects,dict,list,tuple...) ?

**Comment by MahdiZareie** [comment]
and one more thing ..there is already a serializer within <a href="https://docs.djangoproject.com/en/dev/topics/serialization/">django.core</a>.
i think it's reasonable to ask for some options when using a serializer...but i didn't find any option except choosing 'json' as output format :angry:

**Comment by s-soroosh** [comment]
using core serializer in not hard, just you need to say 'json' when you want to call get_serializer.
At all i think this manner needs many effort.
I have found a perfect project with name : django-rest
So you don't need to create view for every model and make it json or some thing else.
I simply have added it in wage_meter and you can see its result in :
http://127.0.0.1:8000/wage_meter/tt/islands/

What do u think about it?
