### ISSUE TITLE
another app for carousel

### ISSUE THREAD

**Issue by MahdiZareie** [s-soroosh/azma-py#12]
after few hours working on carousel and good images followed by some text , i believe this kind of content (in a carousel ) is effective enough to be a dynamic application instead of static unchangeable texts and images.
i believe  
if 
(we hire a good Graphist to provide our images and banners which contains our messages) 
AND 
(pay enough time for writing good and exciting texts for those images) 
THEN
 this little carousel can turn to our fat chance for attracting programmers and Curious students .

**Comment by s-soroosh** [comment]
I have found some one, i will negotiate with him in these days
