### ISSUE TITLE
Improve Exam UI page to use checkbox just for multiple choices

### ISSUE THREAD

**Issue by s-soroosh** [s-soroosh/azma-py#14]
Please update UI to show radio button when just one choice is correct and checkbox for multiple choices questions

**Comment by MahdiZareie** [comment]
در مورد سوالات تک گزینه ای مشکلی وجود داره .
وقتی کاربر یک گزینه رو انتخاب می کنه ، امکان جواب ندادن به سوال رو از دست میده .چون نمیتونه جوابی که داده رو حذف کنه .
دو تا راه به ذهنم رسید :
اول اینکه یک گزینه ای به این قبیل سوالات تک گزینه ای اضافه کنیم که به صورت پیش فرض اون انتخاب شده..گزینه ی"بدون پاسخ"مثلا
یه راه دیگه اینکه وقتی کاربر روی گزینه ای که جواب داده دوباره کلیک کرد ، تیک سوال برداشته بشه .
راه دوم به نظرم بهتره ولی نتونستم پیاده سازیش کنم و دارم تلاش می کنم 
نظر شما چیه ؟

**Comment by s-soroosh** [comment]
جواب ندادن به سوال امتیاز خاصی ندارد و تفاوتی با پاسخ اشتباه ندارد
