### ISSUE TITLE
Using Redis for Applications Setting or session ... what you think ?

### ISSUE THREAD

**Issue by MahdiZareie** [s-soroosh/azma-py#6]
yeki az doostanam redis( http://redis.io/ ) ro behem moarefi kard va az tajrobeye mosbate khodesh baram goft.be nazaram oomad baraye settings application haye projamun mitoonim azash estefade konim ya session hamoon ro toosh zakhire konim.
kolan nazare shoma chie?

**Comment by s-soroosh** [comment]
redis projeye monasebie amma na bara kare ma, ma mikhaym proje ta hade momken lightweight bashe.
Redis baraye jahai ke distributed kar mikonim ya cluster darim monasebe.  be nazaram ma felan too in proje niazi behesh nadarim va faghat developmento kond mikone.
